version: '3'

services:
  web:
    build: ./
    restart: unless-stopped
    container_name: docker-bot
    ports:
      - "443:443"
    networks:
      - web

networks:
  web:
    name: web
    external: false